apiVersion: v1
kind: PersistentVolume
metadata:
  name: metube-nfs
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/part-of: homelab
    type: nfs-utility
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=3
    - nolock
    - soft
    - timeo=30
  nfs:
    path: /mnt/volume1/downloads/youtube
    server: 192.168.1.202
