apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metube-nfs
  namespace: media
  labels:
    app.kubernetes.io/name: metube
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: metube-nfs
  resources:
    requests:
      storage: 500Gi
