apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nextcloud-exporter
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud-exporter
        app.kubernetes.io/part-of: homelab
    spec:
      containers:
        - name: nextcloud-exporter
          image: docker.io/xperimental/nextcloud-exporter:0.9.0
          env:
            - name: NEXTCLOUD_SERVER
              value: "https://cloud.sunnyside.home"
            - name: NEXTCLOUD_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: nextcloud-exporter-credentials
                  key: token
          ports:
            - name: metrics
              containerPort: 9205
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 16Mi
            limits:
              cpu: 50m
              memory: 32Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 10
