---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBiFi937TtCrShmvosK3YyxkqHnA8xQjkyi0Oqw5NsErfcx5iaRkGUwNMjFuQNX7r19zP1Ncjm3sFVAFYzr66N3ZV4SE0+lE99c9smhPXlLafcONtfMCag2dh24iVbBxM1MU3aywNxTM/KzLOz8+da4fKATAwKd6NkitUzAttpt1celCfUaIntxMsLlrSdn68Y/talxwhMbTQV0ESKzUig2acQKxQYG+EDxJty7wl47wUE8ez89iicHwZ+6HbG39rwxp/uzXbAlqEUHKwKxAqFitJq3MBcahsd9tJCBvjK+WMyMJjgDkI8NAqGyTwZkrlpiT/8/YBqykUxCK1YNc0VCkCDWLkstgBxPQ1+ckoeo3SOWqWd44KreG0O7m4X9nXHkuTMKDwCFRXFA3/sRBMvKec3yCN6LnlzagfXvDQrBtfi6ROeURWMtRSDW5zZkQhILgs4RCk2QPt1iJQaacJIKbj5LjrsCuDLWpgvH5wrLEhgqtcHjX69ZvgVPurTamo8V30EzMTJ9jZRTnYyaZ5VffR/5fD1XLPg/0CrgITvEfESgOdfdwCqYJ10lHpT/8PbN/QIJQq71gZ0FeeaDJbGZAEposwaejc4tQm9tnF77uvGcvT6QMYCwaaLFjWHxz/wCNvqI0VsuL73aiRQq5yOs2XKaVylc1mG9syeM/4rdB8fd7ofehRabKU51sT8LA3Oh2iipnafsdeBiylzZp2+y798+wI5ilTl+zuF0oD4=
    admin-user: AgCURsuLJ/qIdARfTw9xp0aMtjxzoaFQFKQ2mFuviaZi8/KrJO9AxsI7V6zbB6UeYOd0lub+xpKZGj7xzA+XFx1CL7wC1LL0qdBzc6MfvwJEjY9mS+DaPOwtEx7F9izNTpy+dRQYnvvRyp1+jt97gylO7xwtoz/fHE9VAOuFPt04mVkc79klnEmMyE3bveMSQzPOc05PJ3SK8IuiP4p2gmcGxuabevuDDYKjo5/fSJEPaELU/lLFWdkfsY1Kg2ImlmuX95k0HbSjSwZexaHbBucXVgqL434rbGmTaYYpLjTCEmmwnJQ9vDUtuMa+BHxlQueF8mbflEQ4JtnLyZafDfafVUv/yfdhqbfDQamsyO0kjIyTQFy7cIcCNaJ8ZRj3wmxNBdGaS/kKcsG6bmPDwOU3SZ99mXUUmQmGUqC8b6ZISsM/BrDjZIhaLkH9oOLY5Z6NVTZaExjsBUJFBoPzoDgAri1FvgpZOGNOnKE6dxzFQvVHwNJScAfekk/lYLL4P4C3NxW/Om3srB1xHo+K9Sno8nyIJjzkP3z7QZCftwYtogUJ0yXqZ1M8Hb4JqGZs5UYyWpBB5KZ2aeSZjESESC8/NlsVn3j5drMgxuHwEVemY++wTjEsxJ394Dg8iCAlauqTXUhv1wY2iJOLJT6rdExmOr1ORbl/Rp+GrQglUcO5VQCW7Uq/NOutj2nwnJO5/f+dzHznFA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
