---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    token: AgCmkn+sWqEEYrPg5BH9onRMlvnAf6SFD+JcjIUbLDiyD1NkBT7ozeN3j4poNdiDyoFL26jQr9TVMfim4xtuXRFgJ0oEi29ZpAoZowMCHNpBWs/jR3MwRbXKwH/umj90Aqq/czyJmq6JtVPx/VmO29OItPLpnFf2ZziWCYCqwhMlWKoL/HwkgFO5sX/GvV6cytvbLac+p2u8lvjSaJB6bvkkW/h2Pslxxf9JkvhBs9OwUpLrSiHK8mopGulC5GBk+XT4uEzTM29xYYb08ygTE6msSfx7WNQg/Ky70Q7qLt/fvBAzp8B8qOXI7C0l5vEl6TaAOLbbqcHNVTMd9sdQDYw4oN+Rnfm8JXzfJaAY+TWIv4sH5iDS+/GorgKKUvUUcSe3deJIb3dv1TsD1RMHy5f/BowhWlQfG3WhP2NN2+EAg7lUvLzOlN/VXfl1Bf2K0WPMNVPA2zAMEtSD/Gis/2A7qPvXYpSJ6FTBOzSGhB4YRHSU9e2dbCV6K08hnRvpAc2L2oi5Y2jDuj/zI7mW81H1mJ0zqXv//s3Rr0uRImwtOu5sWlpQbMnLsOXlC4WvePndLZCh29EpmFvPVvJr8eF+rDdc8woeuRvqYNOeFz7Vu6AlLmVDlp7AuudqvtTGzepiCp7oeFzYXE0xmtTcY3uRsUoghr0rscJXhmtK7oC5CoGVzllbPttRFuZYzkNH9HRLdhAJutoFO9Trpsd8qy1Mxz90T6YnjK/X2w+JiiFkm5VlBCXJoqiHNbg/NkvH4VJ+KFIucAUFkv038046R/mG
  template:
    metadata:
      name: nextcloud-exporter-credentials
      namespace: monitoring
