---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    token: AgCLCqWqeGXk2+ZqUS0maABq6/I93ke0/bSsT9QqylpsG2AcljKQECk/06eNjXAtXTB2+sjwL+8OdoqiBthQDT5XjK0Ohs2r76WyLf5eoWljlHu/hmVZNe7VRjwPVJBZevpjkTKu7PnhMa3ADnp69KcHMQazw3P5vBqh6xHQ4JnJKKhelO7I8UGaVVYfmbw9B23T7Ojt503Tt0qWDcWll5dRjxuAlv+lmzpzPDVUlJu5Iq4P2jLcoqp8BhukSwOL1ZwjJEi3tE+DhrUKmOwsDQynmci4e/I51ifrhfXbrn4OXTwv3+XsJbjYPK3swyDqoMcnVRsgDy5Ry7etYmCGRx+xLHXkthPyt/f1FFmIW9qu+dQxYd40E7SXPm6oZBqz21BKbySl/1jG5gyiB9MAVraqhWQO2NghUBkDxoUXoVFMVSsU94TBAwm5AUb43rJVScFWtIRW0sIO2TrTwu96tHOz5yT3J2I2LCy7T2Nmc4A9ryox39YxxkVdO03AuMLRH6hO/KcOq1Au5xYyzYq+15bizedo58qpnGOKQpGc2qkjO1JbGocdQSKpjNq1FiRdCSaUBA/1pWBX1RTCdl9OnphOoUVxrZOC982mnkVpAtRYS88dMVGIiBABMoFYmTH0GBQohZHQ3/oYkny/M6CntXuk1Zcwbl4ELC2NM3shl+TvARk+jiL9yEI1dUCEzt5wmxkm1iqXdN/WPiyWh+S5JFkKXIll3/KzxnuRvfTr8H1EeHq55nEUoJ8hJFSeA95cjHtR8hZ9fjVRK+FU3mbsTW+g
  template:
    metadata:
      name: nextcloud-exporter-credentials
      namespace: monitoring
    type: Opaque
