---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgA5GDeE/hMKnvYwItDOIFDGw0IB70U14tapYakApxYDFhHihDORg8RPFqh1qh0t6kn0bdN/sxxXrIP81TxQB0c9/y+7nkBwT9C3NKDv55TADrrV9KpHJ2cb4l+kt7bBSS05YtPe/05kTEPU2EZiMxJpyG11pH/x8tVWuEo+q0Gp5/WK+kYfqpAuCYO/UxvaEKoU3bbZp/HYMTevS7hqbxtKrv74xC71mrZG4C+qM5vYz2pnvmKGgLehk0JF2tHhUFnGmXu8zR8+vBzo+YrlrL4EeS/R87FAlmNklov3f0YAtm3UGEepCIyWw98O9mA7YsNlmrFm02i5nSJ98s78jgQz81EQ8Ubapwk8X8gYOWVb18gmO41W5nWNiBL98ERKIaSzP0W6Ozlx012NuiI8X4LPiD5TJAwYrqPC8sv9N/4BfqMrvd4OuVzgMvVKqnJPp/uF+P0J06NrFQg5FM27kIX6ur9aJdE/jQfWSqMVaqDpL+KpUltCvoXF9Wg1dqn9apW2ru5lY7NN2fIF8PIm4OFjTOjoqzEHri/7YI4XYT5UKGj1vg/EZ10RCCCJOLHpHJce8Fz2n99IfbFOtv+ADIYPyi+6Yj4Md9WnbX4aNbzYCFS4XthfH3MhbOgTaqcqXwJJrvZnAAUDpbIwbMtTrEhIsl4gdgIxi9aHUbE96PUhmyGSYMZBkL/TlRTqCXmVxY34atKhqWTbxtAfprOiXDYdOG46HX2i9y0qYddG0UMRRvJRj483NanyHODQpa6VFjadL3nJ1IgUXGYfQ9eKsymNjzasmnFPjUyGVI2C7d3E5II7eif5Do69CPzPqDf4k5k8kNMKV+gbyYw1ght14qHdF9xxWyOswORkEG9acS7knxA=
  template:
    metadata:
      name: proxmox-exporter-config
      namespace: monitoring
