---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgA4vaEUHmFw9XMw+k+g4VUcx1F1uiL4eHLWVe+O8CmObH4QxiJqC28dihBp/i/mCBUglm5d2OZVhcwmxx6F6uDgvTx0fyTD1lCkYXJvYqe90SyDMHdS0r6h4TA2X5LxHTGfLzOUkl1m2P4PhjFeEVKKVGFazKa5brsUElYtnhPaq2EsDN3G0cZPKr1WaYvXGFv/4KiTkTRgYMsObMRGAwpDtWfw6xRxJ++Jdj9OuV+Vn/FlEGQzNFWUhUTDwT/lDMHBfNZY2MaDtD1Qt31JNErmxJKKSokTVPfmaeE+GwB6MMzZX69wQrYXsOUa+wbkQNIz1fcYRFGDTa6uwsCn+Tz8A5WwhXIO4iP2yEIL7QVTK3zmVUC/bYLXJkSJzgZ8JVrWzbE6GergtcAtGrsVvgmiJ+2ZZWQOzg9CnT9Wfm0b3Zv45J9vSIs03QQ5JHP6Dxht8A0nIPydOdqZtRBFWrXHID2kgEtI37QuNxPvtNVHCQQ/4pu7ic6A3QYUL5zkUbIZNC9IS8vh9wWZ7AdU25rq2qEhUZkIGUfYE2B9JDc414vzmFv7Cxi4wYykdR81TNaD96WgMWFTSxV5P9W3CwE7TcWcliBxuhhGzTcksIV7iiAQnS0MlJipr/+WIT29numuCRbYeMwLwTHHeKzz7PnMhqS/aGxAWJBIw89UBIiAw0MOByJ+O6lO7ep1ed5kZ/EDKYVJkPhchTAcMI5fphMCifC9W6RctTWEh3Uf4a55gV0Qr8IsbzJvanloRKMBjxjblOt7OCQcpoR9kUoSekfCLQVGsV8iiBC3XHWtSeQJHz4710nLpBWFFYk2CCH12i5Zlyqw3s1mF6oGCm1xUlvJ1kNDvM8GqLksgN9ndNVYKz3Hbi9iTK6cj26FbE1T
  template:
    metadata:
      name: proxmox-exporter-config
      namespace: monitoring
