---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgCOM/PQ0A/eb+yw0nVWA+C8oMt25W0ZoaZKHEKEzOtFp/12GLvWRWrtxidhdazhCp+BUS7Pq49gNuXC9SDz2TM4WztyXx3QsnWMM9Jz4iub0O467xIzn8Jsq9zBwvmJZ5camZU0N723LEIVMdKMsc58Eh8BEuuFZwTJTwbRKxysFZElGzQQSfZ1/9UUt42ptKmaF3xWO9ZD1g2jDQyByCoYDfxOl6xJj17AZp0jQw0pL75KB+CwF9LOMy4PG4Xeiqhx6Ue07SSvgb8MzxNPqQofprRgRoXogtqifIIPMshCmkKl66NW75c4ZkGReRipLy7L5JBiPkENFULw+ySGUJb2Ky6OPz1it6muYx9hFGZwn9kmAjcKR94aAwnxZUeaELlJ++HZGPfcKgD1l2qYJnxiLn0q1Aw0hhD5rQL02vNsnGarnbjcj+idSunv0MtJNFErhvxbzW+005/5UJhqmdFoeHzaPaod1UWsvCApha+jusOMxoctt0DqWXx4XHDy6BUCxaUnRJltMr6OBGFBrafTbp8GYSMKC08xeE+cXJA0dOD9Gha96Kx3DqkDdNM2jESMkxsD8qT1AStL/Cnrjx7m8LqVBESx/xvnQa446WAEx8WD+0MCJoY2et0FndYhe56BG59ZOLdWPdl0YHGLUb46al+GyEk4AQN3qMhY48E5Tc0e1WNSVhpaHRjUsGtr3E+qrJ2l2djz0jOkoPlMeLKE3mExMZIV6zvVwsWg2XY=
    username: AgAAbkp3GM70zXqsbEWVRcUgw5LNUl1YkJsikv4tTE1AFtfTGmpBf9IC8o2utzlRq1ettibkbMqDLN57vOeKEkMcrgGVS66JkEZVDbQGKi1KuaAbbmqb2IsSeeTIdW7BHg/VyXdVUCZqzJfv1p893Ueu5QSDKqMYWFss4AHW0sKShTTTf5SAXhpDBC5yB3UTcOIs6QhJH4tTfZqU0SDI/k9nB0zEqglhqpnyu68kXs/vJ3oR2kNLxGFseXXcMj95rpv3nse/0A924k2M8gTI7vZS85Lpks5lmRGg0ph0++b/p7+dCs5qiSjsAF8g53rFu1I0Q5oZethDdH92t5UMmBP5hLr0gfgxMrvAyOrNCkyisxDaD6/Q74nSd5H3EHbBME9ovm0fwsaW8Fu8y3Aa6sERI94zPhuB68l6spp2tz/0MRJZrV2k7DWU/7fHZ9OchOjD1WrYiQp+iDPi+4VRno2b1QjSVMwnmUKJn92Ddc3zbQJBAQWR8zpvpCiT7FaVHl7v7jajcBCEtpUyb6AviB7mDo2KK5yKOKDTjmx3Cyb1isKdOAx50A8llB2grFgh+7UpNqMOz7ztRx9Pvid/cv+xVqgjIzBSW1V+WfjDxZ8sDRtfK9DJis99t+pKoFrPf4HcgzO62t9mjrVZOzII3rCs73FR6ymD2n9lWIHacBQsK7v6XM20X4Mr26dyaoveT/2NVsVQrg==
  template:
    metadata:
      name: qbittorrent-exporter-credentials
      namespace: monitoring
    type: Opaque
