apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: qbittorrent-exporter
    app.kubernetes.io/part-of: homelab
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent-exporter
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 15s
