---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCyVLBLAdqOYBxseAJLGqQpFikPmFbfeFpK1n9A/LdNnMtYQdihIf8FaSQqysjvEGp6u0hoiF1WBNyRB8IdUMDURSnjy893Zse5/iMaoAL8heUBbrnWWiefoPpWf95VMMUeys4PrVRHZY1/SsBKOyQTmBFifNGOorY39aGuTh+LUsF2w92ZhbPZ/A0biIdhLaQZSo9ddAosa3mpSwAYAQfJv7szZ5OItCE1Z0viW2wEe7wdqjl3OlRkXX7DXELBWPCmthjwTHT711kfrDWIeEaPWHGV/uSGKaVWRz8znQYzK97mHT/vDmKB8UPEdLJJoDelvUAhUu1bLzM5VAfstJBWyduKLeRPndzXqrorEPmAo07SB0q3yLlhIajtI4/M52S4e7LxEWkBENse0oc1l43dMLSbbKMSbzYcrQqng0ycfwWSqk88f5aRffK6bhVFSknfezChLwXx6GrIzXaYrBPPISZy+ps7yjEQk5hG+Y6l3OKEG5C9x7N+nYE+85jB0UnJR/+Ksj9mvqU02+a1P+KgOVcm2b9ffEO1uD2zq55in2kn/zOoztM8lkw7GVSAzljp/kXl4utraa3UoHcRyiDRRW+O26cVljmVy969Ik9HlsDGifNvZvjYvfHCr+QAn4d4t3ryia5fFhZ2qDqHhW4xXCKeiQ8y33nuD5BS5vNv8FTIcVOLV1/PhVfx0h3J+47DNyYyG/rkY08ZzNAD8VWvhTc/aD65XjBUDiwqjxs=
    admin-user: AgBLpvwzyf1WiztHRSHyE5tQL7k/qVFi2HrwXdmILFkFaleaA63VbKjRsdnYb8hy2RPhzw1PcObMI5eyKrVhYVpjXKzkaz0mZYgWauc/omgmvrfnS2V5gQz2Fi0TSblONk/JVyiZbWKHwrtLS4TyFZSFd2YB65oYtD/aY656HtrAvh14NH14p1Oha/7FvkGrsM6ZGv0RzOgyRuJSO+GaKGSajl+XgmBJ1F4j4m5P1R8e14+2xcLHAyO8hMK8JlsVCXwtIkjLsFncVpMpsX9yLoMo9LOtEbF39gNgJd8xZXRVq7nM4zrytylCqxRJTLwkvOPkZzGBFEDY1dsXqnyONAMFOrlS9HD5HG3nrIhSTddYrZzkUzPFfiMm00PwyPPf9f2VIaJnu8FuXBEvDc44RbpvO/mhdWbLsSaKiWuzZDyl/CmFr4E2egeocdLpaKc8673gFzktYSWQ2rr7EhoBukqxQgqf0AtATIBKhReEVy1ab9as6/jqzpTnFenE8/765cO1FKSJKO5V4QGKJs5nhV/vhkVpWX7NEnNhuYAZ16x4XUUFgUSanv0g52EPNPNye2rC9ESgc7WN6f3kkx4QuUZkWxq5XQ4o/DC3a8rhjiUIgBWvDr6nW3y++L9AQyNIx9ZhXHwpQH5Zc7oZXlkv35DH616nQaiszoQXTp4WQiwspy+Yy1pFbxheOUJSNIo4pg/b91FSjA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
