---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    token: AgCSg2WPPEElNc5eOheSWXyD3gKpHh/KBiEVWyw3GQSLzuelzvb6rpRTGJccHnMGfTwRsljTP8BR019mN3uVPMEE0v96QAvy1WWz/sw5CxYKV1draZ04euQF5LAecSim8vN3uVodXd/jINKsy2NWiccxW67509i9JgxoC7I5Yb+jrGVhBcsbPlsXo8erz/zcokVyVOvYBapSAYfSGkayxogKAoQWcqrW237rAzGOaf1xucNrWHr3eqiZ9hFVv29zObQZaUd5K1BB0mBgzvlLd2agPZ/YvkMql1pKvtObck4Xg2vRj5yuXA17Vc9vIeFAbqsCexX0gkcVV52hq0NyOhONe5Xa54y2zmO9NATkdrkPXLbmh5FZGJOJlLzmoT06Z5jRmksw6/zbVvn8wjoi6azwAnliebMjGFCR6EV29JyZZ588WHlJsteabwesXxva/8alsk6aBhpTEOC1Z/CbtJjw+iX8zsA4dd29egySBJHfrrgdEh2Q8JKjZkAOgZIJ94CERWApMtu7KbVJDfnSooJkpuDujLoJnN48CoccgaK7Z5e/beqLvs6cyTPQY8mVef+g9++OZlLYluF7j/O6STpdzovhzNBqiRTIqk2dIdoW3jC8jzfL1yP7tQhWO8XDyIzMlu9zlAcS0iDMFLQ05iG7Zo6c4Vfc7EM/hSQU2HTByIKvBXP5TrQpp8h0HzsEdwdsdm3ehfJUSiZl7STbPHJndsrW1d8VV8KxRwhy28Eojm2M1u6JtM/EpiW/dJKGHsfREDyR1qPKsjMcq2QnxJFK
  template:
    metadata:
      name: nextcloud-exporter-credentials
      namespace: monitoring
    type: Opaque
