---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nextcloud-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    token: AgAdG7sPAZPfLaDEVgZtKqkWPS+OS6X1hLi/Okly0dFlKl3MciK2xlzjeV1L96duj9AF9cjCQHOKX21lBUMfOsYRrJHw3WjfaNRTqa3uDLPq6p3WeByDc4RoQj4IrzCbxC9cTtqzn3CcM/vwtG3ugjpLWjJpBoZgBH+3s3nkOoyJKB/c5hIkrgirqdv5dUvsdY36pJRsZSRcwTai2hBbee4GCkTtSM/BRkAstfVJsZJHzCrs+RdCVby/+qG5ovaQnCaICFMnCByVIWaSHBopPurjbzDTK9ek0Vsyi3exHSgLDrbSAU37hj2yr9lzI8dS4ltyZ9sTjWCPlKG2yZGN6+cIrFUYeFsxkTxQX/4gkfCVBZvqlwnro4Fxa5X1vsPmNqfplr+1gpwKycuCQcN+UvNTIKIxEQB/Ri3Ql9iReMoHwIxjpqi//7MJhkSiiZ7qiQZj1AMUmQ45nbvJIwpWW4DZN69YFu/1rpcrQFE/rm0fqkXCp8Ib6x/p/ezTrabhfshgnBn9bxiks7hS47vbO/iPjPEKyD1e6UfPN8WDc98B0Ui1vUfDlGk984I+scOnDDmOLMcItxHOv4R7Ir3hPHKFIMkJKwRzq7ZXEfbFDpB5OLAANvmrZzEYENm13yD+qjzAfPks2GuQgREnasHLnoeNvmv0e+JeoCf7WvXq4/7+IuA/XSmXMdyNE3ormYYIr6TlRvQ29iKtZklwqNOfrFR7jqYERinb1nrqq7CSXi5x4HLKYkWbkiyXbCo0A0xSHsiGKdIpjlX32lmtuHd/xNBu
  template:
    metadata:
      name: nextcloud-exporter-credentials
      namespace: monitoring
