---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgBJTqv5WMBztHJaIBoFb+Sol6aL5KO01i+9FUJT6MJhX3vtEMwuHecHMbCvc/1y0ppkOIkE54wTm+LHGWoTm8sqmiD9f8sTt+k8hd9/ajmUBTnZ9lFK8STpodouakGewm8ghAqAEyF0CTl79VkJubTQLVDaFh0JODywenhgQbeEsw4AG5k8ULjG/cMXtt0q3Mrw+vntMNk5whxYBR65F0+Oqg9r4fObV7qIgXBIXjsdB/sGjC66tISN3ER340nJ5RN/ko2OMwtFhkuTr84iY8OOZWUThh3tkoNqt7HqxUr+VFrtJY2nrI8X9ci3goaRcJP0PgoN7+QpIt7jhIWBSNkrXszaA9WxvtZI/oAY9+GPCkJNRgsm1KvvkT3XsRJ2y8TFiRgByp/3f/RdR/TzuCv8r6I+MHOb9myQ3JW7F08qSTtD3hmDxPjppKTX41fqg2dgJWJeMyhSo3LBD0BPXid6RowWnKk5sYN0a+U20scvbOsq/utxD3CBEImQy86miHpzQNZPqw4APn8J1tzZwQCA9Wjbn4wqEUkYReaiPj/1howgTW7+CGWxUXMQSAy0mLaqyNAOLmF88XZhqtgMHP5mWhB72YdPO4JMHLzWCnrKT982mKp8J71woE9rcQ6+kgwJkK5AN+E8KbcF2OvPHHwzQGqyAqLeDDxZmIfxI706/b++rtK7OzmQLLj+8Q/nRnPLuXfFx2VbLnsIQOzlGpvZ232najg6Wdt60lCfspu+ZGEdOSi7eFlt31EZ1DNjDLGihRSXQM/HURKHm9uIRx5cydCPxO3UzIU8LIsvkw9Df38UIAxqaA/XPsEg0VN+mmM4k/esl9+/6pkR4tshJ1vXU+6UI9xVHXnfuoooEtcLBSHTfSQ2vpNqnfEBj4Kv
  template:
    metadata:
      name: proxmox-exporter-config
      namespace: monitoring
