---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-exporter-config
  namespace: monitoring
spec:
  encryptedData:
    pve.yml: AgBSvCoJd8axOni5kJ/axSNyscnaunJHRTHL2SeYBukzKsRVfe9FphLdK+Q7ZduLVVzzhqmHxNmPiF3p+s4fxWqfFC5/Y5z7zk7sob67ESVidexQdQgw5SQ/2vFYJItRb7jVhr0H7knl54/Q4ZhtKJX9vOADqP9atQ6QSEvrfZhD/wg4Fp3AxwtVY98RACg3gPkT1l2+B59E2z0II1bxRJ1NHFQh2PHIhlBhbtjyjNvcy6pkn34uRYQWZ0bCRcVp/+7f4Cu8wr44Y/GSQOJBCCdbABRY8AyjHNmU6uWb08LM60rgfghwZI02igJl2ETeLG68cIuhL6paptjMFYHtOvc/la8mBdwJDaHyFQf9Ocy2YgEjnwZ3IphKoyT5kHNCGjDfyp7wnC1Tl8dHlQe4bmIdRUT+UFVoXvQRYJHAMa99ELzMplC7//DfOtBWsqXUX5qNtxh6N47lhflBFmixidqXEA2s82dULF8K1Qmd4yQLJALX0losDmpPne4QUCRSJWYfrqB2A8UUyuRbycR3D+b1gQiHF+YtEqVL3ikc+WFOhcnjn9wt9j0bIGIdBooXq1b7g++EExmQUh15Uz9PES43EqZOTlgVVX8KMqYpGHkBtSOrT0ZZZ1QuwmIDJv4kZ32iY6zobBzBUzvKV0DfsFLREt+zF5ToWrAAvvMljzxY1u9fxoLcrFqEw4/X6AuOsBWPMrTBq5k8pgI6mxsv35+CxIOemPRpLvaDUs9Euo223KONgqVqLSqzAFErJ6fGSSaucCO3JHt+9evA2eHj2ZiG7NZ69bzcxQ8m2GuDrEWPfZHzJgdxyDDc/utyXTTO30cViffiDtjqDGJnLSkkff4vyCjJ3hxP6IDiRIULFxqqDpI=
  template:
    metadata:
      name: proxmox-exporter-config
      namespace: monitoring
