---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: qbittorrent-exporter-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgDWySrIu1ajOz2KB08C2+EJUK+nJ9X6q6lRmEddBhO9kluNuvpOo76mbECR/nNzJUsdN+psYqyi+k/dMUPer17q+oS8Z05ESg3AHZyrYIfhP2sj9LGHF8FjzuOp5RGjHdIl7L2pIZ4NZmMIIUv4V90Fl9nPiC+y7PcIMCxfCkT+tgzbuZSEH0fyhanzqdWhdCko/qPkc8oHAJFtkIo3hLlYH5x4KQVfetXW54QhT/CvuFTTIuRzQ6h8lquHOJSt3b73dlv+2I2vGUqStlGtqK9iV6nLvKOZxQva7bM5EJPY38zx+H8BD0T+vPt0GJhUoGidVSj1eEc6o5TSSFXjrXX42x6ZjH0JeKeNW1yzGacv5kv0yvo51O0U/8G6CIUaq1wFY1qznDDGGfSK2Gt7ieZxHe+oy+LjlaV2mhI9bDiASWW2e6wKnt19T3ctwG5j5seSUrnPfk4bEplCk4ZiIs22EcNNMYApRI+QUU3RgnAgOyr7Zf+FO9wgTaAX0miPkRzaA1beFs8dMCZoQXqzbw9+aAuNxq76+0nOToGRugbCW9Vl9BTDS+N3vOW3nnHiQqoNGX3Qj2P1W4hY8piYK1Au0Uo+mtf+XmBCyl8u7umqvfLKLGciOjo5YgV93ZP0sNbqHvzkIIiKmGMkm4paB2Ny5PDpw8yV/X45mbXTQidrN7IquSoCBLbbDXTQ4rRyvM7kjHGD8XyWfSLJduq1OkI7Jt9WKcp+LOENrQD/PS8=
    username: AgAu7c4iYGNCGCmaC0mlb7fODmNeycZwfz24i0hbl0TTxFhaPGUIfUtyN5/7PQQH4FCLPgwPLNcOLKF6BNK0v26qASs1t3JWk4hi97Zg7IGeJXGP34NgEjsJbJnFNQbHtd6j1/5tg2BcmzIclfZFqzwLoNWYFaJSdNyhWz0jI9tmWEvTgdSCqet89KAFTUQwEYqhqjLy1Nq4xlto7kJkCnpsCU8A6gbJ+WKL9HjNe8s2SRu9yI3/HSrw7GFbuFymVluGXSb5tvwBuWWQAf6Ebrw0G820MMpdfN9APXk09JuoTUQheWi0RepFE9v8AO2C04zLWfxUX5xSmZ92Sfn2r/HfKLaCkehdYDBw5ZsLpmzFif+zlSZ8Osh5Du9UfNKgJZMh1gGrLkmI4p/EXphQmivGq4ZvZSg+3i7QFdFYoTx6Zbh3p9gdNLv53rMTmR+5+2qA0ipdyIS+cIa/QABzG660pOA6ENa8Az9k80DNhsnwPZgxN7BPJ1bHZwWvE414JvTWzX1wWvpz7T0Bo5bhqaEDE154rCyCLRjZ6PmM5nEVDrKe4Wdx1QNwBMWinAqdlNyM+Y2ey5DXu7a0PXHKbWpK2dGyE+JhdhFJAF7oT2h0UNslolcgmyvhytsB1zn+ORQtz3KKWWXckiM173WqdvzpGiKZ8YxVxp0t+ZCtma2Mkc64g6fusgj26DrUz+LK5CLANKYSng==
  template:
    metadata:
      name: qbittorrent-exporter-credentials
      namespace: monitoring
    type: Opaque
