apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/infra

patches:
  - target:
      kind: Ingress
      name: guacamole
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging-guac.sunnyside.home
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging-guac.sunnyside.home
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-guacamole-tls

  - target:
      kind: Ingress
      name: uptime-kuma
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging-uptime.sunnyside.home
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging-uptime.sunnyside.home
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-uptime-kuma-tls

  - target:
      kind: Ingress
      name: netalertx
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: staging-netalertx.sunnyside.home
      - op: replace
        path: /spec/tls/0/hosts/0
        value: staging-netalertx.sunnyside.home
      - op: replace
        path: /spec/tls/0/secretName
        value: staging-netalertx-tls
