apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
  namespace: productivity
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-extensions
  namespace: productivity
  labels:
    app.kubernetes.io/name: freshrss
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
