apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
  labels:
    app.kubernetes.io/name: plex
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
