apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: productivity
  labels:
    app.kubernetes.io/name: mealie
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi
