apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guacamole-db-data
  namespace: infra
  labels:
    app.kubernetes.io/name: guacamole-db
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
