apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-data
  namespace: productivity
  labels:
    app.kubernetes.io/name: searxng
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
