apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netalertx-config
  namespace: infra
  labels:
    app.kubernetes.io/name: netalertx
    app.kubernetes.io/part-of: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
