apiVersion: v1
kind: Service
metadata:
  name: netalertx
  namespace: infra
  labels:
    app.kubernetes.io/name: netalertx
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: netalertx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 20211
