apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
  namespace: infra
  labels:
    app.kubernetes.io/name: uptime-kuma
    app.kubernetes.io/part-of: homelab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: uptime-kuma
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3001
