apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - unpoller
  - proxmox-exporter
  - truenas-graphite
  - exportarr
  - qbittorrent-exporter
  - macos-node-exporter
  - nextcloud-exporter
