apiVersion: v1
kind: Service
metadata:
  name: proxmox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: proxmox-exporter
    app.kubernetes.io/part-of: homelab
spec:
  selector:
    app.kubernetes.io/name: proxmox-exporter
  ports:
    - name: metrics
      port: 9221
      targetPort: metrics
      protocol: TCP
