apiVersion: v1
kind: Service
metadata:
  name: unpoller
  namespace: monitoring
  labels:
    app.kubernetes.io/name: unpoller
    app.kubernetes.io/part-of: homelab
spec:
  selector:
    app.kubernetes.io/name: unpoller
  ports:
    - name: metrics
      port: 9130
      targetPort: metrics
      protocol: TCP
