apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: utilities
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/part-of: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homepage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homepage
        app.kubernetes.io/part-of: homelab
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: TZ
              value: Europe/Dublin
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: home.sunnyside.home
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          volumeMounts:
            - name: config
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: config
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: config
          configMap:
            name: homepage-config
